### ISSUE TITLE
Possible memory leak

### ISSUE THREAD

**Issue by htfy96** [xplorld/XorLinkedList#1]
When T is copy-throwable and an exception is raised in tail->join and catched outside newList, the memory of previous nodes will be leaked.
Suggestion:
A: use try-destruct-throw wrapper
or B: add typename=typename enable_if<typename is_nothrow_constructible<T>::value>::type in newList

**Comment by xplorld** [comment]
@htfy96 Thanks.
 I did not quite understand your B solution. Can you give a snippet demonstrating it?

**Comment by xplorld** [comment]
see this:
https://github.com/xplorld/XorLinkedList/commit/2191a43e7d0bf8407770d3759a57279c0e2d53ff
is that ok?
@htfy96

**Comment by htfy96** [comment]
``` cpp
    Node *list,*tail;
    try {
        assert(begin != end && "input feed is empty");
        list = new Node(&*begin); //cast iter to pointer
        ++begin;
        tail = list;
        while (begin != end){

            tail = tail->join(&*begin);
            ++begin;
        }
    } catch(...) {
        delete list;
        throw;
    }
```

Unfortunately this is still buggy. If `new Node` in `list = new Node(&*begin);` throws an exception, then `list` won't be assigned and remain as an uninitialized value. After that `delete list` will delete an uninitialized pointer. Therefore you should initialize `list` explicitly by `Node *list = nullptr` because `delete nullptr` is well-defined(do nothing).

**Comment by xplorld** [comment]
What now?
https://github.com/xplorld/XorLinkedList/commit/ad1f9b07f677f078d76a18bf1638b357332d0b23
@htfy96

**Comment by htfy96** [comment]
Besides, the ctor of `Node` should be defined `noexcept` whenever possible because STL will use much simpler algorithm to handle your object in this case.

``` cpp
template < typename inputIterator>
        Node(const inputIterator v);
```

to

``` cpp
template < typename inputIterator>
        Node(const inputIterator v) 
noexcept(std::is_nothrow_constructible<T, const inputIterator>::value)
```

**Comment by xplorld** [comment]
wow thanks.

**Comment by xplorld** [comment]
If T throws from copy constructor,

``` cpp
template < typename inputIterator>
        Node(const inputIterator v);
```

would throw. My catch just do the delete, and rethrows the exception. Is it still `noexcept`?

**Comment by htfy96** [comment]
If T throws from copy ctor, 

``` cpp
noexcept(std::is_nothrow_constructible<T, const inputIterator>::value)
```

will be

``` cpp
noexcept(false)
```

,
therefore `Node(const inputIterator v)` is **not** `noexcept` under this circumstance.

As for `newList`, in all cases it could throw exception due to `new`, thus it can't be `noexcept`.

**Comment by xplorld** [comment]
Brilliant!

**Comment by xplorld** [comment]
is that mean `newList` and `Node` ctor and `XorLinkedList` ctor should all mark `noexcept(...)` ?

**Comment by htfy96** [comment]
1. For `newList`, it can't be `noexcept` due to `new`, neither can the ctors of `XorLinkedList`
2. For ctor of `Node`, `noexcept(...)` is recommended because 
   1. the `noexcept` property of ctor is important since many functions in STL rely on it
   2. the condition of `noexcept` is simple

Some people recommend use `noexcept` in the following way, but I think it might be too aggressive:

``` cpp
void foo()
    noexcept(
        noexcept(f()) && // here noexcept is an operator
        noexcept(g())
    )
{
    f();
    g();
}
```
